apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gue0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-waoa-tenant/rhtap-demo-app/hacbs-test-project-gue0@sha256:7b4557b21b3d33e9855fa5a555eee539c009550b5cf3a22b67454dde0037b112
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
