apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gue0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gue0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gue0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gue0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gue0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-waoa-tenant/rhtap-demo-app/hacbs-test-project-gue0@sha256:0033c5ac3130344b74833eb748a24ff72b50400cd100a69aba9628402ebd9dd3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
